### ISSUE TITLE
USGDA001 - authentification

### ISSUE THREAD

**Issue by ghdiginamic** [2019-d05-code/gestion-des-absences-front#1]
En tant qu'employé (tous profils confondus), je souhaite pouvoir m'authentifier afin de pouvoir accéder aux fonctionnalités de l'application.

# Critères d'acceptation :

* [x] L'application donne accès à une page d'authentification
![](https://github.com/DiginamicFormation/ressources-atelier/raw/master/gestion-des-absences/Authentification.png)

* [x] La page d'authentification est accessible via le chemin http://[domaine]/connexion.
* [x] La page d'authentification contient un logo (proposé par le développeur)
* [x] La page d'authentification contient le titre GDA - Gestion Des Absences
* [x] La page d'authentification contient les champs Email et Mot de passe
* [x] Le bouton "Se connecter" permet de valider les informations saisies
* [x] Si les informations saisies ne permettent pas d'authentifier l'utilisateur, le message d'erreur "Vos informations d'authentification sont invalides.".
![](https://github.com/DiginamicFormation/ressources-atelier/raw/master/gestion-des-absences/Authentification.invalide.png)

* [x] En cas d'authentification avec succès le collaborateur est redirigé vers la page d'accueil contenant le menu.
* [x] Les chemins de l'application sont sécurisés.

**Comment by Julie-Ylsh** [comment]
Le Front est OK - Manque :
- [ ] Dans auth.service, requête vers le back à écrire
- [ ] redirection vers la bonne page après succès de connexion
- [ ] chemins à sécuriser
