### ISSUE TITLE
USGDA002 - Déconnexion

### ISSUE THREAD

**Issue by ghdiginamic** [2019-d05-code/gestion-des-absences-front#2]
En tant qu'employé authentifié, je souhaite pouvoir me déconnecter de l'application.

# Critères d'acceptation :

* [x] Les pages de l'application (en dehors de l'écran d'authentification), doivent posséder un lien "Se déconnecter"
* [x] Le lien "Se déconnecter"  :
  * rend inaccessible les pages de l'application (en dehors de l'écran d'authentification)
  * redirige l'utilisateur vers l'écran d'authentification.

**Comment by Julie-Ylsh** [comment]
Url pour la déconnexion : /logout
