### ISSUE TITLE
USGDA005 - menu employé

### ISSUE THREAD

**Issue by ghdiginamic** [2019-d05-code/gestion-des-absences-front#5]
En tant qu'employé j'ai accès aux fonctionnalités de menu suivantes: 
Accueil, Gestion des absences, Planning des absences, Jours feriés

![](https://github.com/DiginamicFormation/ressources-atelier/raw/master/gestion-des-absences/Accueil.admin.png)

**Comment by Julie-Ylsh** [comment]
Attention : 
- [ ] régler souci de la barre de navigation qui se déroule pas

**Comment by Julie-Ylsh** [comment]
> Attention :
> 
> * [ ]  régler souci de la barre de navigation qui se déroule pas

#3 #4
